# Generated by Django 6.0.7 on 2026-09-08 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('EUR', 'EUR (€)'), ('USD', 'USD ($)'), ('GBP', 'GBP (£)'), ('JPY', 'JPY (¥)')], default='EUR', max_length=3)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=10000, max_digits=14)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paramètres utilisateur',
                'verbose_name_plural': 'Paramètres utilisateurs',
            },
        ),
    ]
