# Generated by Django 6.0.7 on 2026-09-08 23:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ouverture', models.DateTimeField(verbose_name="Date d'ouverture")),
                ('date_fermeture', models.DateTimeField(verbose_name='Date de fermeture')),
                ('paire', models.CharField(choices=[('EUR/USD', 'EUR/USD'), ('GBP/USD', 'GBP/USD'), ('USD/JPY', 'USD/JPY'), ('USD/CHF', 'USD/CHF'), ('AUD/USD', 'AUD/USD'), ('USD/CAD', 'USD/CAD'), ('NZD/USD', 'NZD/USD'), ('EUR/GBP', 'EUR/GBP'), ('GBP/JPY', 'GBP/JPY'), ('XAU/USD', 'XAU/USD (Or)'), ('BTC/USD', 'BTC/USD'), ('ETH/USD', 'ETH/USD')], max_length=20)),
                ('direction', models.CharField(choices=[('achat', 'Achat (Long)'), ('vente', 'Vente (Short)')], max_length=10)),
                ('taille', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Taille (lots)')),
                ('strategie', models.CharField(choices=[('Scalping', 'Scalping'), ('Day Trading', 'Day Trading'), ('Swing Trading', 'Swing Trading'), ('Breakout', 'Breakout'), ('Range', 'Range'), ('News Trading', 'News Trading'), ('Grid', 'Grid'), ('DCA', 'DCA')], max_length=30)),
                ('session', models.CharField(blank=True, choices=[('Asiatique', 'Asiatique'), ('Européenne', 'Européenne'), ('Américaine', 'Américaine'), ('Overlap', 'Overlap')], max_length=20)),
                ('prix_entree', models.DecimalField(decimal_places=5, max_digits=14)),
                ('prix_sortie', models.DecimalField(decimal_places=5, max_digits=14)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True)),
                ('resultat_pips', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Résultat (pips)')),
                ('resultat_monetaire', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Résultat (devise)')),
                ('commission_swap', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('humeur_avant', models.CharField(blank=True, choices=[('Confiant', 'Confiant'), ('Stressé', 'Stressé'), ('Neutre', 'Neutre'), ('Excited', 'Excité'), ('Fatigué', 'Fatigué')], max_length=20)),
                ('humeur_apres', models.CharField(blank=True, choices=[('Satisfait', 'Satisfait'), ('Déçu', 'Déçu'), ('Frustré', 'Frustré'), ('Content', 'Content'), ('Indifférent', 'Indifférent')], max_length=20)),
                ('respect_plan', models.BooleanField(default=True, verbose_name='Respect du plan')),
                ('commentaires', models.TextField(blank=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'gif'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_ouverture', '-created_at'],
                'indexes': [models.Index(fields=['user', '-date_ouverture'], name='trades_trad_user_id_58cf06_idx')],
            },
        ),
    ]
